services:
  test-alpine-edge:
    build:
      context: .
      dockerfile: test/docker/alpine-edge
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-alpine-latest:
    build:
      context: .
      dockerfile: test/docker/alpine-latest
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-archlinux:
    build:
      context: .
      dockerfile: test/docker/archlinux
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-centos-stream9:
    build:
      context: .
      dockerfile: test/docker/centos-stream9
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-debianstable:
    build:
      context: .
      dockerfile: test/docker/debianstable
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-debiantesting:
    build:
      context: .
      dockerfile: test/docker/debiantesting
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-fedora41:
    build:
      context: .
      dockerfile: test/docker/fedora41
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-fedora42:
    build:
      context: .
      dockerfile: test/docker/fedora42
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-opensuseleap:
    build:
      context: .
      dockerfile: test/docker/opensuseleap
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-opensusetumbleweed:
    build:
      context: .
      dockerfile: test/docker/opensusetumbleweed
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-ubuntu2204:
    build:
      context: .
      dockerfile: test/docker/ubuntu2204
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-ubuntu2404:
    build:
      context: .
      dockerfile: test/docker/ubuntu2404
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
