= timew-annotate(1)

== NAME
timew-annotate - add an annotation to intervals

== SYNOPSIS
[verse]
*timew annotate* [_<id>_**...**] _<annotation>_

== DESCRIPTION
The 'annotate' command is used to add an annotation to an interval.

See the 'summary' command on how to display the _<id>_ and _<annotation>_ of an interval.

== EXAMPLES
*Annotate a single interval*::
+
Call the command with an _id_ and the _annotation_:
+
[source]
----
$ timew annotate @2 'Lorem ipsum'
Annotated @2 with "Lorem ipsum"
----

*Remove an annotation*::
+
Annotating an interval with an empty string removes the annotation:
+
[source]
----
$ timew annotate @1 ''
Removed annotation from @1
----

*Annotate multiple intervals*::
+
You can annotate multiple intervals with the same _annotation_ at once, by specifying their ids:
+
[source]
----
$ timew annotate @2 @10 @23 'Lorem ipsum'
Annotated @1 with "Lorem ipsum"
Annotated @10 with "Lorem ipsum"
Annotated @23 with "Lorem ipsum"
----

*Annotate the current open interval*::
+
If there is active time tracking, you can omit the ID when you want to add an annotation to the current open interval:
+
[source]
----
$ timew start foo
...
$ timew annotate bar
Annotated @1 with "bar"
----
+
This results in the current interval having tag 'foo' and annotation 'bar'.

== pass:[BUGS & LIMITATIONS]
The summary command truncates annotations longer than 15 characters.
To display longer annotations, one can use the 'export' command, or a custom report.

Currently, the annotation command picks the last token from the command line and uses it as annotation.
I.e. using no quotes in an annotation command like

[source]
----
$ timew annotate @1 lorem ipsum
----

will result in interval @1 having only 'ipsum' as its annotation.
Use quotes to avoid this.

== SEE ALSO
**timew-export**(1),
**timew-summary**(1),
**timew-tag**(1)
