= timew-summary(1)

== NAME
timew-summary - display a time-tracking summary

== SYNOPSIS
[verse]
*timew summary* [_<range>_] [_<tag>_**...**]

== DESCRIPTION
Displays a report summarizing tracked and untracked time for the current day by default.
Accepts date ranges and tags for filtering, or shortcut hints:

    $ timew summary monday - today
    $ timew summary :week
    $ timew summary :month

The ':ids' hint adds an 'ID' column to the summary report output for interval modification.

The ':annotations' hint adds an 'Annotation' column to the summary report output.
The annotation column is limited to 15 characters.
Longer values in this column are truncated to 12 characters and shown with an ellipsis attached.

== CONFIGURATION
**reports.summary.annotations**::
Determines whether the annotation column is shown in the summary.
Can be overridden by the ':annotations' and ':no-annotations' hint, respectively.
Default value is 'no'

**reports.summary.holidays**::
Determines whether relevant holidays are shown beneath the report.
Can be overridden by the ':holidays' and ':no-holidays' hint, respectively.
Default value is 'yes'.

**reports.summary.ids**::
Determines whether the id column is shown in the summary.
Can be overridden by the ':ids' and ':no-ids' hint, respectively.
Default value is 'no'.

**reports.summary.tags**::
Determines whether the tags column is shown in the summary.
Can be overridden by the ':tags' and ':no-tags' hint, respectively.
Default value is 'yes'.

**reports.summary.range**::
Set the date range for the summary report.
The value has to be a range hint, see timew-hints(7).
Default value is ':day'

**tags.**__<tag>__**.color**::
Assigns a specific foreground and background color to a tag.
Examples of valid colors include 'white', 'gray8', 'black on yellow', and 'rgb345'.

== SEE ALSO
**timew-day**(1),
**timew-lengthen**(1),
**timew-modify**(1),
**timew-month**(1),
**timew-shorten**(1),
**timew-tag**(1),
**timew-untag**(1),
**timew-week**(1)
