#! usr/bin/env python

import sys

# for each holidays.??-?? file:
#   extract locale from file name
#   compose holidata.net URL
#   download file
#   for each line in downloaded file
#     convert to timewarrior format
#     write to holiday file

