name: tests
permissions:
  contents: read
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Alpine Edge"
            runner: ubuntu-latest
            container: alpine-edge
          - name: "Alpine Latest"
            runner: ubuntu-latest
            container: alpine-latest
          - name: "Archlinux Base"
            runner: ubuntu-latest
            container: archlinux
          - name: "Centos Stream9"
            runner: ubuntu-latest
            container: centos-stream9
          - name: "Debian Stable"
            runner: ubuntu-latest
            container: debian-stable
          - name: "Debian Testing"
            runner: ubuntu-latest
            container: debian-testing
          - name: "Fedora 41"
            runner: ubuntu-latest
            container: fedora-41
          - name: "Fedora 42"
            runner: ubuntu-latest
            container: fedora-42
          - name: "OpenSUSE Leap"
            runner: ubuntu-latest
            container: opensuse-leap
          - name: "OpenSUSE Tumbleweed"
            runner: ubuntu-latest
            container: opensuse-tumbleweed
          - name: "Ubuntu 22.04"
            runner: ubuntu-latest
            container: ubuntu-2204
          - name: "Ubuntu 24.04"
            runner: ubuntu-latest
            container: ubuntu-2404
          - name: "macOS 14"
            runner: macos-14
            container: osx-14
          - name: "macOS 15"
            runner: macos-15
            container: osx-15
    runs-on: ${{ matrix.runner }}
    continue-on-error: ${{ matrix.continue-on-error == true }}
    steps:
      - uses: actions/checkout@v5
      - name: Build ${{ matrix.name }}
        env:
          DOCKER_REGISTRY: docker.pkg.github.com
          DOCKER_CACHE_IMAGE: docker.pkg.github.com/${{ github.repository }}/timewarrior_cache
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTAINER: ${{ matrix.container }}
        run: if [[ !( "${CONTAINER}" =~ osx-* ) ]] ; then docker compose build "test-${CONTAINER}" ; fi
      - name: Test ${{ matrix.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTAINER: ${{ matrix.container }}
        run: if [[ !( "${CONTAINER}" =~ osx-* ) ]]; then docker compose run "test-${CONTAINER}" ; else bash test/scripts/test_osx.sh ; fi
